### PR TITLE
first attempt at addressing #71

### PR DESCRIPTION
**Pull request by dret**
feedback and comments very welcome! #71

### CODE REVIEW

**Comment by dret** [comment]
this might need to be tweaked depending on the publication plan for this spec, but at least it's a starting point that can be used when the spec moves forward.

**Comment by marcoscaceres** [comment]
@dret, would you mind joining the WICG? (go to https://www.w3.org/community/wicg/, click on join/leave button).

This is substantial contribution, so we need an IPR commitment before we can review it.

**Comment by dret** [comment]
On 2018-06-26 11:40, Marcos Cáceres wrote:
> @dret <https://github.com/dret>, would you mind joining the WICG? (go to 
> https://www.w3.org/community/wicg/, click on join/leave button).
> This is substantial contribution, so we need an IPR commitment before we 
> can review it.

ok, i am trying. but it seems that updating the affiliation takes a 
while, so i'll have to wait for w3c to get that done before i can join. 
i hope it won't take too long.

**Comment by marcoscaceres** [comment]
@dret, cool, thanks for joining (just got the email)... just need you to link your W3C account and Github account: 
https://www.w3.org/users/myprofile/connectedaccounts

**Comment by dret** [comment]
On 2018-06-27 09:47, Marcos Cáceres wrote:
> @dret <https://github.com/dret>, cool, thanks for joining (just got the 
> email)... just need you to link your W3C account and Github account:
> https://www.w3.org/users/myprofile/connectedaccounts

done, thanks for pointing me to the right place.

**Review by marcoscaceres — APPROVED** [review]
Looks ok to me, but @igrigorik should give final approval.

**Review by igrigorik — APPROVED** [review]
👍

**Comment by igrigorik** [comment]
Looks great, thanks Erik! Merging.

**Pull request merged**
