### PR TITLE
In the Browser Support table, show Android Firefox

### PR DESCRIPTION
**Pull request by sideshowbarker**
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/netinfo/pull/86.html" title="Last updated on May 11, 2020, 4:31 AM UTC (184c4eb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/netinfo/86/0746409...184c4eb.html" title="Last updated on May 11, 2020, 4:31 AM UTC (184c4eb)">Diff</a>

### CODE REVIEW

**Review by marcoscaceres — APPROVED** [review]

**Comment by sideshowbarker** [comment]
Thanks!

**Comment by marcoscaceres** [comment]
heh, I we should check if Firefox actually supports these things... I don't know who is feeding caniuse this data - pretty certain we don't support the whole spec.

**Comment by sideshowbarker** [comment]
See the (more-granular) BCD data:

* https://github.com/mdn/browser-compat-data/blob/master/api/Navigator.json#L427
* https://github.com/mdn/browser-compat-data/blob/master/api/NetworkInformation.json

…that at least correctly shows several members of `NetworkInformation` aren’t implemented in Android Firefox.

Can I Use should probably be updated to show Android Firefox only has partial support.

**Comment by marcoscaceres** [comment]
ReSpec also supports `"mdn": true`... so that data should also show up inline. Will check.

**Comment by marcoscaceres** [comment]
@sideshowbarker, ok, enabled `mdn` data (give it the ol' shift-refresh)... now get a better view of things at a more granular level.

**Comment by sideshowbarker** [comment]
@marcoscaceres This reminds me that I’ve been meaning to suggest an enhancement to the MDN annotations generated by Respec: We can add an implementation-status indicator to the collapsed MDN buttons. Take a look at https://wicg.github.io/webusb/#device-usage

The (Bikeshed-generated) MDN annotations there shout pretty loudly (maybe too loudly…) that `USBDevice` is only implemented in one engine.

Then for comparison, go to https://drafts.csswg.org/css-logical-1/#caption-side and scroll down. The implementation-status indicators in the MDN annotations there are pretty useful. The CSS Logical Properties and Values spec is a mix of features at varying levels of implementation maturity: some implemented in all engines, some in two engines, and some only in one engine. A reader can get a pretty quick sense of which are which just with quick scroll through the spec.

Due to the baroque complexity of BCD status data for some features, programatically identifying whether a particular browser currently supports a particular feature requires some work. But I’ve already done that work — three times: Once in Free Pascal (for the HTML spec) and once in Python (for Bikeshed) and once also in JavaScript (for https://github.com/w3c/mdn-spec-links).

We could re-use the same algorithm for Bikeshed — and probably also copy over the JavaScript code for it that I already have. I’ve been meaning to write a Bikeshed patch for it, but haven’t managed to get around to it quite yet.

**Comment by marcoscaceres** [comment]
@sideshowbarker, oh, that's awesome... I'll copy/paste the above to a ReSpec bug. Maybe we can convince @sidvishnoi to sneak that in :)

**Comment by marcoscaceres** [comment]
Filed https://github.com/w3c/respec/issues/2861

**Pull request merged**
